version: '3'

services:

  app:
    entrypoint:  dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    container_name: app
    build:
      context: ./node
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db: 
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    networks:
      - fullcycle
    ports:
      - "8080:80"
    depends_on:
      - app
     

volumes:
  mysql_data:
    driver: local

networks:
  fullcycle: 
    driver: bridge




